# Generated by Django 6.0.2 on 2026-02-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='binding_type',
            field=models.CharField(blank=True, choices=[('hard', 'Тверда'), ('soft', 'М’яка')], max_length=10, null=True, verbose_name='Тип палітурки'),
        ),
    ]
